<a href="https://colab.research.google.com/github/OscarPasasin/datamining/blob/main/Notebooks/Ejercicio2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
import pandas as pd
import numpy as np
from itertools import combinations

In [5]:
url = "https://raw.githubusercontent.com/OscarPasasin/datamining/refs/heads/main/archivos/prueba/Ejercicio%202.csv"
df = pd.read_csv(url)
df.head()

,Elapsed_Time,Time_in_Community,Gender,Working,Age,Family,Hobbies,Social_Club,Political,Professional,Religious,Support_Group
0,8.71,Short,M,No,53,1,0,0,0,0,0,0
1,5.24,Medium,F,No,31,0,0,0,0,0,1,1
2,4.22,Medium,M,No,42,1,1,0,0,1,0,0
3,4.81,Long,F,No,30,0,0,0,0,0,0,0
4,3.95,Long,M,Yes,29,0,0,0,1,1,0,1

In [6]:
df.shape

(3483, 12)

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3483 entries, 0 to 3482
Data columns (total 12 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Elapsed_Time       3483 non-null   float64
 1   Time_in_Community  3483 non-null   object
 2   Gender             3483 non-null   object
 3   Working            3483 non-null   object
 4   Age                3483 non-null   int64
 5   Family             3483 non-null   int64
 6   Hobbies            3483 non-null   int64
 7   Social_Club        3483 non-null   int64
 8   Political          3483 non-null   int64
 9   Professional       3483 non-null   int64
 10  Religious          3483 non-null   int64
 11  Support_Group      3483 non-null   int64
dtypes: float64(1), int64(8), object(3)
memory usage: 326.7+ KB

In [8]:
df.isnull().sum()

Elapsed_Time         0
Time_in_Community    0
Gender               0
Working              0
Age                  0
Family               0
Hobbies              0
Social_Club          0
Political            0
Professional         0
Religious            0
Support_Group        0
dtype: int64

In [9]:
df.duplicated().sum()

np.int64(5)

In [10]:
df.describe()

,Elapsed_Time,Age,Family,Hobbies,Social_Club,Political,Professional,Religious,Support_Group
count,3483.000000,3483.000000,3483.000000,3483.000000,3483.000000,3483.000000,3483.000000,3483.000000,3483.000000
mean,5.921786,36.730692,0.389894,0.300029,0.188056,0.093885,0.324433,0.418605,0.158771
std,2.293446,10.646524,0.487796,0.458336,0.390813,0.291710,0.468230,0.493401,0.365515
min,2.010000,17.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,3.875000,27.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,5.930000,36.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
75%,7.840000,46.000000,1.000000,1.000000,0.000000,0.000000,1.000000,1.000000,0.000000
max,10.150000,57.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000

In [11]:
df["Elapsed_Time"].describe()

count    3483.000000
mean        5.921786
std         2.293446
min         2.010000
25%         3.875000
50%         5.930000
75%         7.840000
max        10.150000
Name: Elapsed_Time, dtype: float64

In [12]:
df["Age"].describe()

count    3483.000000
mean       36.730692
std        10.646524
min        17.000000
25%        27.000000
50%        36.000000
75%        46.000000
max        57.000000
Name: Age, dtype: float64

In [16]:
variables_numericas = ["Elapsed_Time", "Age"]

for columna in variables_numericas:
    media = df[columna].mean()
    desviacion = df[columna].std()

    limite_inferior = media - 2 * desviacion
    limite_superior = media + 2 * desviacion

    outliers = df[
        (df[columna] < limite_inferior) |
        (df[columna] > limite_superior)
    ]

    print("Variable:", columna)
    print("Media:", round(media, 2))
    print("Desviación estándar:", round(desviacion, 2))
    print("Límite inferior:", round(limite_inferior, 2))
    print("Límite superior:", round(limite_superior, 2))
    print("Cantidad de valores atípicos:", len(outliers))
    print("-" * 40)

Variable: Elapsed_Time
Media: 5.92
Desviación estándar: 2.29
Límite inferior: 1.33
Límite superior: 10.51
Cantidad de valores atípicos: 0
----------------------------------------
Variable: Age
Media: 36.73
Desviación estándar: 10.65
Límite inferior: 15.44
Límite superior: 58.02
Cantidad de valores atípicos: 0
----------------------------------------

In [17]:
df["Time_in_Community"].value_counts()

Time_in_Community
Long      1465
Medium    1304
Short      714
Name: count, dtype: int64

In [18]:
df["Gender"].value_counts()

Gender
F    1790
M    1693
Name: count, dtype: int64

In [19]:
df["Working"].value_counts()

Working
Yes    1744
No     1739
Name: count, dtype: int64

In [20]:
columnas_asociacion = [
    "Family",
    "Hobbies",
    "Social_Club",
    "Political",
    "Professional",
    "Religious",
    "Support_Group"
]

In [21]:
df_asociacion = df[columnas_asociacion].copy()
df_asociacion.head()

,Family,Hobbies,Social_Club,Political,Professional,Religious,Support_Group
0,1,0,0,0,0,0,0
1,0,0,0,0,0,1,1
2,1,1,0,0,1,0,0
3,0,0,0,0,0,0,0
4,0,0,0,1,1,0,1

In [22]:
for columna in columnas_asociacion:
    print(columna, df_asociacion[columna].unique())

Family [1 0]
Hobbies [0 1]
Social_Club [0 1]
Political [0 1]
Professional [0 1]
Religious [0 1]
Support_Group [0 1]

In [23]:
df_asociacion_bool = df_asociacion.astype(bool)

df_asociacion_bool.head()

,Family,Hobbies,Social_Club,Political,Professional,Religious,Support_Group
0,True,False,False,False,False,False,False
1,False,False,False,False,False,True,True
2,True,True,False,False,True,False,False
3,False,False,False,False,False,False,False
4,False,False,False,True,True,False,True

In [24]:
df_asociacion_bool.dtypes

Family           bool
Hobbies          bool
Social_Club      bool
Political        bool
Professional     bool
Religious        bool
Support_Group    bool
dtype: object

In [26]:
frecuencias = df_asociacion.sum().sort_values(ascending=False)
frecuencias

Religious        1458
Family           1358
Professional     1130
Hobbies          1045
Social_Club       655
Support_Group     553
Political         327
dtype: int64

In [27]:
porcentajes = (df_asociacion.mean()*100).sort_values(ascending=False)
porcentajes.round(2)

Religious        41.86
Family           38.99
Professional     32.44
Hobbies          30.00
Social_Club      18.81
Support_Group    15.88
Political         9.39
dtype: float64

In [28]:
for grupo_a, grupo_b in combinations(columnas_asociacion, 2):
    soporte = (df_asociacion_bool[grupo_a] & df_asociacion_bool[grupo_b]).mean()

    if soporte > 0.10:
        print(grupo_a, "+", grupo_b, "=", round(soporte, 4))

Family + Hobbies = 0.1869
Family + Social_Club = 0.1289
Family + Professional = 0.1303
Family + Religious = 0.2245
Hobbies + Social_Club = 0.1235
Hobbies + Religious = 0.2389
Social_Club + Religious = 0.1473
Professional + Religious = 0.124

In [29]:
df_asociacion_bool.head()

,Family,Hobbies,Social_Club,Political,Professional,Religious,Support_Group
0,True,False,False,False,False,False,False
1,False,False,False,False,False,True,True
2,True,True,False,False,True,False,False
3,False,False,False,False,False,False,False
4,False,False,False,True,True,False,True

In [30]:
df_asociacion_bool.to_csv("Ejercicio_2_preparado.csv",index=False)